//
// Created by noartem on 30.06.2022.
//

#include "DiaryEntryElement.h"

Element *diaryEntryElement(DiaryEntry *entry) {
    return border()
        ->setWidth(2)
        ->setColor("#E5BEBD")
        ->setRadius(6)
        ->setChild(rounded()
            ->setRadius(6)
            ->setChild(background()
                ->setColor("#FFFFFF")
                ->setChild(padding()
                    ->setPaddings(12)
                    ->setChild(column()
                        ->setSpacing(4)
                        ->appendChild(row()
                            ->setSpacing(6)
                            ->appendChild(width()
                                ->setWidth(160)
                                ->setChild(text()
                                    ->setFontColor("#2B1615")
                                    ->setFontSize(16)
                                    ->setFontWeight(600)
                                    ->setText("Date and Time")))
                            ->appendChild(text()
                                ->setFontColor("#2B1615")
                                ->setFontSize(16)
                                ->setText(entry->getDatetimeFormatted())))
                        ->appendChild(row()
                            ->setSpacing(6)
                            ->appendChild(width()
                                ->setWidth(160)
                                ->setChild(text()
                                    ->setFontColor("#2B1615")
                                    ->setFontSize(16)
                                    ->setFontWeight(600)
                                    ->setText("Duration")))
                            ->appendChild(text()
                                ->setFontColor("#2B1615")
                                ->setFontSize(16)
                                ->setText(entry->getDurationFormatted())))
                        ->appendChild(row()
                            ->setSpacing(6)
                            ->appendChild(width()
                                ->setWidth(160)
                                ->setChild(text()
                                    ->setFontColor("#2B1615")
                                    ->setFontSize(16)
                                    ->setFontWeight(600)
                                    ->setText("Place")))
                            ->appendChild(text()
                                ->setFontColor("#2B1615")
                                ->setFontSize(16)
                                ->setText(entry->getPlace())))))));
}
